### ISSUE TITLE
Getting undefined "canvas" error

### ISSUE THREAD

**Issue by KingMob** [swevans/canvas-resizer#1]
This line:
`var ctx = canvas.getContext('2d');` in the `resize()` function
gives me an undefined error, since there is no "canvas" in scope, only `this._canvas`.

**Comment by swevans** [comment]
Thanks for reporting the issue @KingMob. I just committed a fix and a couple other touch ups to get around some typescript compilation errors. The ts and js files are patched. Thanks again!
